export const CourseAction = {
  // Auth
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  // Users
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",

  // Courses
  COURSE_CREATED: "COURSE_CREATED",
  COURSE_UPDATED: "COURSE_UPDATED",
  COURSE_DELETED: "COURSE_DELETED",
  COURSE_PUBLISHED: "COURSE_PUBLISHED",
  COURSE_UNPUBLISHED: "COURSE_UNPUBLISHED",

  // Sections
  SECTION_CREATED: "SECTION_CREATED",
  SECTION_UPDATED: "SECTION_UPDATED",
  SECTION_DELETED: "SECTION_DELETED",

  // Lessons
  LESSON_CREATED: "LESSON_CREATED",
  LESSON_UPDATED: "LESSON_UPDATED",
  LESSON_DELETED: "LESSON_DELETED",

  // Enrollment
  ENROLLMENT_CREATED: "ENROLLMENT_CREATED",
  ENROLLMENT_CANCELLED: "ENROLLMENT_CANCELLED",

  // Payments
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
} as const;

export type CourseActionType = (typeof CourseAction)[keyof typeof CourseAction];
