export const EnrollmentAction = {
  ENROLLMENT_CREATED: "ENROLLMENT_CREATED",
  ENROLLMENT_MANUALLY_GRANTED: "ENROLLMENT_MANUALLY_GRANTED",
  ENROLLMENT_CANCELLED: "ENROLLMENT_CANCELLED",
  ENROLLMENT_EXPIRED: "ENROLLMENT_EXPIRED",
  ENROLLMENT_RESTORED: "ENROLLMENT_RESTORED",

  COURSE_ENROLLED: "COURSE_ENROLLED",
  COURSE_UNENROLLED: "COURSE_UNENROLLED",

  ACCESS_GRANTED: "ACCESS_GRANTED",
  ACCESS_REVOKED: "ACCESS_REVOKED",
} as const;

export type EnrollmentActionType =
  (typeof EnrollmentAction)[keyof typeof EnrollmentAction];
