export const LessonAction = {
  LESSON_CREATED: "LESSON_CREATED",
  LESSON_UPDATED: "LESSON_UPDATED",
  LESSON_DELETED: "LESSON_DELETED",

  LESSON_PUBLISHED: "LESSON_PUBLISHED",
  LESSON_UNPUBLISHED: "LESSON_UNPUBLISHED",

  LESSON_MOVED: "LESSON_MOVED",
  LESSON_REORDERED: "LESSON_REORDERED",

  LESSON_VIDEO_UPDATED: "LESSON_VIDEO_UPDATED",
  LESSON_PREVIEW_ENABLED: "LESSON_PREVIEW_ENABLED",
  LESSON_PREVIEW_DISABLED: "LESSON_PREVIEW_DISABLED",
} as const;

export type LessonActionType = (typeof LessonAction)[keyof typeof LessonAction];
